Added Cart
HrishikeshMahalle/Bad_Gamer-Ecom-website pull request #3
Opened 2022-02-15 18:28 UTC by HrishikeshMahalle

2022-02-17 13:38 UTC, agrawalshanu708 commented
Try to consistent with colors, my suggestion to make background color light..and else is looking good

2022-02-17 13:48 UTC, HrishikeshMahalle commented
> Try to consistent with colors, my suggestion to make background color light..and else is looking good



> @agrawalshanu708  Sure i'll look into it, initially thought of making the website theme darker but the color seletion went quite terrible so will try to update that once Merged. Thank you

2022-02-17 17:27 UTC, AshutoshM29 requested changes
UI looks good!
Just a suggestion, you are using too many high-quality images which are taking a lot of time to load your website, you should optimize your images!!

> @AshutoshM29 Will surely work over that as well, since i'll add more images, will keep a note of this.. Thank You!!!!

2022-02-17 17:46 UTC, AshutoshM29 approved these changes

2022-02-17 18:16 UTC, md-amir-gauhar commented on Cart/cart.css
> +    background-color: #f3ec78;
Try using variables for colors

2022-02-17 18:17 UTC, md-amir-gauhar commented on styles.css
> +    background-repeat: no-repeat;
Delete unused/commented codes

2022-02-17 18:18 UTC, md-amir-gauhar approved these changes

2022-02-18 04:52 UTC, Hamza-777 approved these changes
Everything looks good! Just make the changes amir suggested.

2022-02-18 18:24 UTC, merged